services:
  wingtech-bot:
    image: wingtech-bot
    container_name: wingtech-bot
    ports:
      - 8080:80
    restart: unless-stopped

    # These values come from .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - postgres

